@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}

###

# Get all books
GET {{host}}/books HTTP/1.1

###

# Get a book
GET {{host}}/books/1?_embed=personas HTTP/1.1

###

# Create a book
POST {{host}}/books HTTP/1.1
content-type: application/json

{
  "title": "Redpaws's red paw",
  "image": "",
  "personas": [
    1,
    2
  ]
}

###

# Update a book
PATCH {{host}}/books/1 HTTP/1.1
content-type: application/json

{
  "title": "Into the Wilds"
}

###

# Delete a book
DELETE {{host}}/books/3 HTTP/1.1

###

# Get all personas
GET {{host}}/personas HTTP/1.1

###

# Create a persona
POST {{host}}/personas HTTP/1.1
content-type: application/json

{
  "name": "Cinderpelt",
  "description": "Gray she-cat",
  "image": ""
}

###

# Update a persona
PATCH {{host}}/personas/1 HTTP/1.1
content-type: application/json

{
  "name": "edited",
}


# Delete a personas
DELETE {{host}}/personas/5 HTTP/1.1

###

# Get all arcs
GET {{host}}/arcs HTTP/1.1

###

# Get an arcf
GET {{host}}/arcs/1 HTTP/1.1

###

# Create an arc
POST {{host}}/arcs HTTP/1.1
content-type: application/json

{
  "title": "Broken Code",
  "importance": 5
}

###

# Update an arc
PATCH {{host}}/arcs/3 HTTP/1.1
content-type: application/json

{
  "title": "Broken Codes"
}

###

# Delete an arc
DELETE {{host}}/arcs/3 HTTP/1.1