spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wcbc-database
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Or 'validate' in production
preload:
  database: false